apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jarvis-auth.fullname" . }}
  labels: {{- include "jarvis-auth.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "jarvis-auth.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "jarvis-auth.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: auth
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          {{- if .Values.envFromSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.envFromSecret | quote }}
          {{- end }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
