image:
  repository: ghcr.io/cis1912/jarvis-notes
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1
service:
  port: 8001

env:
  DATABASE_URL: "postgresql://jarvis:password@jarvis-platform-postgresql.monitoring.svc.cluster.local:5432/jarvis"
  AUTH_SERVICE_URL: "http://jarvis-auth-jarvis-auth:8000"
  FRONTEND_URL: "http://localhost:3000"
  DEBUG: "False"

resources:
  requests: { cpu: 50m, memory: 128Mi }
  limits:   { cpu: 500m, memory: 512Mi }
