apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jarvis-auth
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/logbrass/dev_ops.git
    targetRevision: HEAD
    path: charts/jarvis-auth
    helm:
      valueFiles:
        - ../../environments/aws/jarvis-auth.values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: jarvis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
